### ISSUE TITLE
serde support?

### ISSUE THREAD

**Issue by rbtcollins** [MidasLamb/non-empty-string#3]
Very nice. Wanted to use it in a project making API calls where a specific field should not be empty, rather than just not-be-missing, but there was no Serde support :/.

**Comment by MidasLamb** [comment]
I'll work on integrating that!

**Comment by MidasLamb** [comment]
It's present in [v0.2.0] ([crates.io])

[v0.2.0]: https://github.com/MidasLamb/non-empty-string/releases/tag/v0.2.0
[crates.io]: https://crates.io/crates/non-empty-string

**Comment by MidasLamb** [comment]
Fixed in #4
